name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 23.7.0
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'
          cache: 'npm'

      - name: Upgrade to npm 11.1.0
        run: npm install -g npm@11.1.0

      - name: Confirm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: xvfb-run -a npm run test
