name: Run Tests

on:
  pull_request:
    branches:
      - '**' # Match all branches
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.7.0
          check-latest: true

      - name: Check versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test